server: server.cpp
	g++ server.cpp -o server

client: client.cpp
	g++ client.cpp -o client

raspberry: raspberry.cpp header/communication_layer.h source/communication_layer.cpp
	g++ raspberry.cpp source/communication_layer.cpp -o raspberry
	